In [66]:
import gensim
from gensim.models import Word2Vec,KeyedVectors
import pandas as pd
import numpy as np
import nltk
import os
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [55]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [59]:
from google.colab import files
uploaded = files.upload()

Saving 1 - A Game of Thrones.txt to 1 - A Game of Thrones (1).txt
Saving 2 - A Clash of Kings.txt to 2 - A Clash of Kings (1).txt
Saving 3 - A Storm of Swords.txt to 3 - A Storm of Swords (1).txt
Saving 4 - A Feast for Crows.txt to 4 - A Feast for Crows (1).txt
Saving 5 - A Dance with Dragons.txt to 5 - A Dance with Dragons (1).txt


In [62]:
story=[]

for filename in uploaded.keys():
    with open(filename, encoding='utf-8', errors='ignore') as f:
        corpus = f.read()

    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [63]:
len(story)

158874

In [64]:
story

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [68]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2,
    workers=4
)

In [69]:
model.build_vocab(story)

In [70]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(6574306, 8625265)

In [71]:
model.wv.most_similar('daenerys')

[('stormborn', 0.7806184887886047),
 ('targaryen', 0.7767819762229919),
 ('princess', 0.716821014881134),
 ('unburnt', 0.7162420153617859),
 ('rhaegar', 0.7076355218887329),
 ('doran', 0.7052602767944336),
 ('elia', 0.7051975727081299),
 ('myrcella', 0.6907604336738586),
 ('margaery', 0.6894134879112244),
 ('queen', 0.6797250509262085)]

In [72]:
model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'jon'

In [73]:
model.wv.doesnt_match(['cersei', 'jaime', 'bronn', 'tyrion'])

'bronn'

In [74]:
model.wv['king']

array([ 2.8233933 , -0.23667037, -1.668429  , -1.5667586 , -3.2546885 ,
        2.626305  ,  1.5781467 ,  0.12626947, -0.35906416,  1.4111798 ,
       -1.9313488 , -0.37000158, -2.2477765 , -0.6928875 , -0.77744454,
       -2.4032338 ,  1.456478  , -1.4176506 , -4.1815777 , -2.403072  ,
        2.7841346 ,  2.4469476 ,  0.66785467, -2.323547  , -0.17614157,
        1.2634593 , -1.7456352 , -0.3944301 ,  0.32337824,  3.3388305 ,
       -0.4663792 ,  2.432233  , -1.598412  , -2.3282852 ,  1.4362594 ,
        1.6312256 ,  0.41925016, -1.0307636 , -0.89854443,  0.96767694,
       -1.1198499 ,  0.8617738 ,  0.88778716,  1.1822093 ,  0.13282742,
       -2.8321764 ,  0.6888652 ,  0.7933397 ,  0.10142624, -0.26433027,
       -0.11174989, -0.18530959,  1.9571358 , -1.2948539 , -1.0613031 ,
       -0.77501816, -1.7574915 ,  0.69934595,  0.37489513, -0.0138949 ,
        1.4824841 ,  0.12669301,  2.0265667 ,  2.162249  ,  0.535482  ,
       -1.3576685 ,  0.15398054,  1.5198976 , -0.22365147,  1.23

In [75]:
model.wv.similarity('cersei','sansa')

np.float32(0.7733629)

In [76]:
model.wv.similarity('tywin','sansa')

np.float32(0.25435084)

In [77]:
model.wv.get_normed_vectors()

array([[ 0.07213514,  0.06532126,  0.0513271 , ..., -0.08974673,
         0.04196546,  0.06666457],
       [ 0.05602081, -0.07342751,  0.0769151 , ..., -0.03092553,
        -0.03847349,  0.09649275],
       [-0.02055744, -0.10903431, -0.13267477, ..., -0.03249376,
         0.1782701 , -0.15488903],
       ...,
       [-0.08382579,  0.02597964, -0.16387786, ...,  0.02046986,
         0.11104724, -0.1128337 ],
       [-0.00656017,  0.06179194,  0.03676665, ..., -0.08674654,
        -0.00887254, -0.07392911],
       [ 0.14842184, -0.07983606,  0.11571676, ...,  0.01179769,
         0.01756795, -0.02621624]], dtype=float32)

In [78]:
y = model.wv.index_to_key

In [79]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'them',
 'lord',
 'no',
 'from',
 'were',
 'would',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'could',
 'are',
 'we',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'king',
 'who',
 'well',
 'down',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'old',
 'hand',
 'even',
 'too',
 'before',
 'never',
 'tyrion',
 'off',
 'an',
 'know',
 'see',
 'into',
 'made',
 'father',
 'now',
 'eyes',
 'black',
 'told',
 'thought',
 'lady',
 'time',
 'then',
 'how',
 'long',
 'has',
 'might',
 'us',
 'come',
 'where',
 'here',
 'can',
 'through',
 'still',
 'face',
 'head',
 'red',
 'way',
 'page',
 'boy',
 'must',
 'once',
 'good',
 'two',
 'over',
 'little',
 'about',
 'brother'

In [82]:
from sklearn.decomposition import PCA

pca=PCA(n_components=3)
X = pca.fit_transform(model.wv.get_normed_vectors())



In [83]:
X[:5]

array([[ 0.22756411,  0.59481114, -0.03247628],
       [ 0.20108084,  0.34969854,  0.02501436],
       [-0.24123637,  0.58585185,  0.21452028],
       [ 0.04594789,  0.38430685, -0.10890511],
       [-0.06689225,  0.55746466,  0.24533588]], dtype=float32)

In [88]:
import plotly.express as px
px.scatter_3d(X[:100],x=0,y=1,z=2,color=y[:100])