In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({
    'text': [
        'people watch campusx',
        'campusx watch campusx',
        'people write comment',
        'campusx write comment'
    ],
    'output': [1, 1, 0, 0]
})

df

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


In [4]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(ngram_range=(1,3))

In [5]:
bow=cv.fit_transform(df['text'])

In [6]:
print(cv.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}


In [7]:
print(bow.toarray())

[[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0]
 [2 1 1 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 1 1 0 0 1 1 0 0 1 1]
 [1 0 0 1 1 1 0 0 0 0 0 0 0 1 1]]


In [8]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1]])

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(ngram_range=(1,2))
tfidf.fit_transform(df['text']).toarray()

array([[0.35285549, 0.        , 0.        , 0.        , 0.43584673,
        0.55281632, 0.        , 0.43584673, 0.43584673, 0.        ,
        0.        ],
       [0.64868222, 0.50814302, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.40062579, 0.40062579, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.4222466 , 0.4222466 ,
        0.        , 0.53556627, 0.        , 0.        , 0.4222466 ,
        0.4222466 ],
       [0.35285549, 0.        , 0.55281632, 0.43584673, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.43584673,
        0.43584673]])

In [18]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.91629073 1.91629073 1.51082562 1.51082562 1.91629073
 1.91629073 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'campusx watch' 'campusx write' 'comment' 'people'
 'people watch' 'people write' 'watch' 'watch campusx' 'write'
 'write comment']
